### ISSUE TITLE
over/under-time as function of fiber location

### ISSUE THREAD

**Issue by pmelchior** [tianshu-wang/PFS-GNN-bipartite#2]
We effectively assume that all nodes are equivalent, which isn't entirely true because some of our fibers are at the edge fo the field. I wonder if that has influence on the violation of the constraints. Could you make a plot of the over/under time as function of focal plane position.

**Comment by tianshu-wang** [comment]
Here it is:
![fiberlayout](https://user-images.githubusercontent.com/31485874/122620797-e0fcc880-d061-11eb-8af3-fc8615bd021b.png)

**Comment by pmelchior** [comment]
ok, this looks insignificant. Good!
